package com.arcaeic.osrs.BarracudaTrialHelmLock.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ObjectID;

@RequiredArgsConstructor
@Getter
public enum SailFacility
{

	LINEN(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_LINEN,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_LINEN,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_LINEN,
		}
	),
	CANVAS(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_CANVAS,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_CANVAS,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_CANVAS,
		}
	),
	COTTON(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_COTTON,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_COTTON,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_COTTON,
		}
	),
	BLACK(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLACK,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLACK,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLACK,
		}
	),
	YELLOW(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_YELLOW,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_YELLOW,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_YELLOW,
		}
	),
	PURPLE(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PURPLE,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PURPLE,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PURPLE,
		}
	),
	GREEN(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_GREEN,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_GREEN,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_GREEN,
		}
	),
	BLUE(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLUE,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLUE,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLUE,
		}
	),
	PINK(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PINK,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PINK,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PINK,
		}
	),
	RED(
		new int[]{
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_RED,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_RED,
			ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_RED,
		}
	);

	private final int[] gameObjectIds;

}
